from typing import Dict, Any
from qwed_tax.verifier import TaxVerifier

class QWEDTaxMiddleware:
    """
    The "Swiss Cheese Defense" Safety Layer.
    Intercepts AI requests meant for execution engines (like Gusto or Avalara) 
    and mathematically verifies the tax logic before allowing the API call to proceed.
    """
    def __init__(self):
        # Initialize the US tax verifier engine, specifically grabbing the payroll guard.
        self.tax_verifier_engine = TaxVerifier(jurisdiction="US").payroll

    def process_ai_payroll_request(self, ai_generated_payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Intercepts an AI-generated payroll payload meant for Gusto.
        Verifies the gross-to-net logic to prevent tax calculation hallucinations.
        
        Args:
            ai_generated_payload: The raw JSON/dict payload generated by the AI agent.
            
        Returns:
            A decision dictionary indicating whether execution is permitted.
        """
        # Extract the core payroll entry that needs mathematical validation
        payroll_entry = ai_generated_payload.get("payroll_entry", {})
        
        # Verify deterministic logic via the QWED tax verification engine
        result = self.tax_verifier_engine.verify_gross_to_net(payroll_entry)
        
        # Check the deterministic verification result
        if not result.get("verified", False):
            # The AI hallucinated math or tax rules. Block the outbound request.
            return {
                "status": "BLOCKED",
                "risk": "TAX_LOGIC_HALLUCINATION",
                "reason": result.get("error", "Failed deterministic verification."),
                "execution_permitted": False
            }
            
        # The AI's logic is mathematically sound. Allow execution to Gusto.
        return {
            "status": "VERIFIED",
            "message": "AI tax logic mathematically verified. Safe to execute.",
            "execution_permitted": True,
            "validated_payload": ai_generated_payload
        }
