import logging
from typing import Dict, Any
from pydantic import ValidationError
from qwed_tax.verifier import TaxVerifier
from qwed_tax.models import PayrollEntry, VerificationResult

_logger = logging.getLogger(__name__)

class QWEDTaxMiddleware:
    """
    The "Swiss Cheese Defense" Safety Layer.
    Intercepts AI requests meant for execution engines (like Gusto or Avalara) 
    and mathematically verifies the tax logic before allowing the API call to proceed.
    """
    def __init__(self):
        # Initialize the US tax verifier engine.
        self.tax_verifier = TaxVerifier(jurisdiction="US")

    def process_ai_payroll_request(self, ai_generated_payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Intercepts an AI-generated payroll payload meant for Gusto.
        Verifies the gross-to-net logic to prevent tax calculation hallucinations.
        
        Args:
            ai_generated_payload: The raw JSON/dict payload generated by the AI agent.
            
        Returns:
            A decision dictionary indicating whether execution is permitted.
        """
        # Extract the core payroll entry that needs mathematical validation
        payroll_entry_data = ai_generated_payload.get("payroll_entry")
        if not payroll_entry_data:
            return {
                "status": "BLOCKED",
                "risk": "INVALID_PAYLOAD",
                "reason": "Missing or empty 'payroll_entry' in payload.",
                "execution_permitted": False,
            }
        
        try:
            payroll_entry = PayrollEntry.model_validate(payroll_entry_data)
        except ValidationError as exc:
            return {
                "status": "BLOCKED",
                "risk": "INVALID_PAYLOAD",
                "reason": f"Payload failed schema validation: {exc}",
                "execution_permitted": False,
            }
        
        # Verify deterministic logic via the QWED tax verification engine
        try:
            result = self.tax_verifier.verify_us_payroll(entry=payroll_entry)
            if not isinstance(result, VerificationResult):
                return {
                    "status": "BLOCKED",
                    "risk": "VERIFIER_ERROR",
                    "reason": "Tax verifier returned an unexpected result type.",
                    "execution_permitted": False,
                }
        except Exception as exc:
            _logger.exception("TaxVerifier raised an unexpected error")
            return {
                "status": "BLOCKED",
                "risk": "VERIFIER_ERROR",
                "reason": "Tax verifier raised an unexpected internal error.",
                "execution_permitted": False,
            }
        
        # Check the deterministic verification result
        if not result.verified:
            # The AI hallucinated math or tax rules. Block the outbound request.
            return {
                "status": "BLOCKED",
                "risk": "TAX_LOGIC_HALLUCINATION",
                "reason": result.message,
                "execution_permitted": False
            }
            
        # The AI's arithmetic is mathematically sound, but arithmetic alone
        # is NOT full tax verification. Block execution until legal checks
        # (classification, withholding, reciprocity, filing) are implemented.
        return {
            "status": "ARITHMETIC_VERIFIED",
            "message": (
                "Gross-to-net arithmetic verified. Legal/tax classification, "
                "withholding legality, reciprocity, and filing obligations "
                "were NOT checked. Execution blocked until full verification."
            ),
            "execution_permitted": False,
            "checks_run": ["gross_to_net_arithmetic"],
            "checks_not_run": [
                "worker_classification",
                "withholding_legality",
                "reciprocity",
                "filing_obligations",
            ],
            "validated_payload": payroll_entry.model_dump(mode="json"),
        }
